#!/bin/bash -e

ORG_PATH="github.com/coreos-inc"
REPO_PATH="${ORG_PATH}/rkt"

if [ ! -h gopath/src/${REPO_PATH} ]; then
	mkdir -p gopath/src/${ORG_PATH}
	ln -s ../../../.. gopath/src/${REPO_PATH} || exit 255
fi

export GOBIN=${PWD}/bin
export GOPATH=${GOPATH}:${PWD}/gopath

eval $(go env)

echo "Building acfmt..."
go build -o $GOBIN/acfmt ${REPO_PATH}/app-container/acfmt

echo "Building ACE validator..."
GOOS=linux CGO_ENABLED=0 go build -a -ldflags '-extldflags "-static"' -o $GOBIN/ace_validator ${REPO_PATH}/app-container/ace

echo "Building rkt (stage0)..."
go build -o $GOBIN/rkt ${REPO_PATH}/cmd

echo "Building init (stage1)..."
go build -o $GOBIN/init ${REPO_PATH}/stage1

echo "Building metadatasvc..."
go build -o $GOBIN/metadatasvc ${REPO_PATH}/metadatasvc
