#!/bin/bash -e
#
# Run all rocket tests
# ./test
# ./test -v
#
# Run tests for one package
#
# PKG=./app-container/discovery ./test
# PKG=cas ./test

# Invoke ./cover for HTML output
COVER=${COVER:-"-cover"}

source ./build

TESTABLE_AND_FORMATTABLE="app-container/discovery app-container/schema/types cas pkg/tar"
FORMATTABLE="$TESTABLE_AND_FORMATTABLE app-container/ace app-container/aci app-container/actool app-container/schema metadatasvc path pkg/io pkg/proc pkg/tarheader rkt stage0/run.go stage1 version"

# user has not provided PKG override
if [ -z "$PKG" ]; then
	TEST=$TESTABLE_AND_FORMATTABLE
	FMT=$FORMATTABLE

# user has provided PKG override
else
	# strip out leading dotslashes and trailing slashes from PKG=./foo/
	TEST=${PKG/#./}
	TEST=${TEST/#\//}
	TEST=${TEST/%\//}

	# only run gofmt on packages provided by user
	FMT="$TEST"
fi

# split TEST into an array and prepend REPO_PATH to each local package
split=(${TEST// / })
TEST=${split[@]/#/${REPO_PATH}/}

echo "Running tests..."
go test -timeout 60s ${COVER} $@ ${TEST} --race

echo "Validating app manifest..."
bin/actool validate app-container/examples/app.json

echo "Validating container runtime manifest..."
bin/actool validate app-container/examples/container.json

echo "Checking gofmt..."
fmtRes=$(gofmt -l $FMT)
if [ -n "${fmtRes}" ]; then
	echo -e "gofmt checking failed:\n${fmtRes}"
	exit 255
fi

echo "Checking govet..."
vetRes=$(go vet $TEST)
if [ -n "${vetRes}" ]; then
	echo -e "govet checking failed:\n${vetRes}"
	exit 255
fi

echo "Success"
