#!/bin/bash -e
#
# Run all rkt tests
# ./test
# ./test -v
#
# Run tests for one package
#
# PKG=./store ./test
# PKG=store ./test

# Invoke ./cover for HTML output
COVER=${COVER:-"-cover"}

source ./build

TESTABLE_AND_FORMATTABLE="pkg/keystore pkg/lock pkg/tar rkt rkt/config stage1/init store"
FORMATTABLE="$TESTABLE_AND_FORMATTABLE common networking stage0/run.go version"

# user has not provided PKG override
if [ -z "$PKG" ]; then
	TEST=$TESTABLE_AND_FORMATTABLE
	FMT=$FORMATTABLE

# user has provided PKG override
else
	# strip out leading dotslashes and trailing slashes from PKG=./foo/
	TEST=${PKG/#./}
	TEST=${TEST/#\//}
	TEST=${TEST/%\//}

	# only run gofmt on packages provided by user
	FMT="$TEST"
fi

# split TEST into an array and prepend REPO_PATH to each local package
split=(${TEST// / })
TEST=${split[@]/#/${REPO_PATH}/}

echo "Running tests..."
go test -timeout 60s ${COVER} $@ ${TEST} --race

echo "Checking gofmt..."
fmtRes=$(gofmt -l $FMT)
if [ -n "${fmtRes}" ]; then
	echo -e "gofmt checking failed:\n${fmtRes}"
	exit 255
fi

echo "Checking govet..."
vetRes=$(go vet $TEST)
if [ -n "${vetRes}" ]; then
	echo -e "govet checking failed:\n${vetRes}"
	exit 255
fi

# Functional tests are more dangerous than unit tests: they use 'sudo' and access
# /var/lib/rkt/ directly. Only run them inside well-known CI systems.
if [ "$CI" == true ] ; then
	if [ "${CIRCLECI}" == true -o "${SEMAPHORE}" == true ] ; then
		echo "Checking functional tests..."
		(cd tests && ./test)
	else
		echo "Functional tests disabled."
	fi
else
	echo "Functional tests disabled."
fi

echo "Success"
