// Copyright 2015 The rkt Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"strings"
)

const (
	// depMkTemplate holds a template for file-based dependency
	// tracking make file.
	depMkTemplate = `# generated by depsgen

define _DEPS_GEN_GET_ALL_FILES_
$(eval _DEPS_GEN_ALL_FILES_ := !!!DEPS_GEN_FILES_GENERATOR!!!)
$(strip $(_DEPS_GEN_ALL_FILES_)) \
$(eval _DEPS_GEN_ALL_FILES_ :=)
endef

_DEPS_GEN_ALL_FILES_STORED_ := !!!DEPS_GEN_ALL_FILES_STORED!!!

_DEPS_GEN_SPACE_ :=
_DEPS_GEN_SPACE_ +=

_DEPS_GEN_F1_ := $(sort $(strip $(_DEPS_GEN_ALL_FILES_STORED_)))
_DEPS_GEN_F2_ := $(sort $(strip $(call _DEPS_GEN_GET_ALL_FILES_)))

ifeq ($(_DEPS_GEN_F1_),$(_DEPS_GEN_F2_))

!!!DEPS_GEN_TARGET!!!: $(_DEPS_GEN_ALL_FILES_STORED_)

else

# invalidate the target
!!!DEPS_GEN_TARGET!!!: _DEPS_GEN_INVALIDATE_
.PHONY: _DEPS_GEN_INVALIDATE_

endif

_DEPS_GEN_GET_ALL_FILES_ :=
_DEPS_GEN_ALL_FILES_STORED_ :=
_DEPS_GEN_SPACE_ :=
_DEPS_GEN_F1_ :=
_DEPS_GEN_F2_ :=
`
)

// Generate returns contents of make file describing dependencies of
// given target on given files and checking if files weren't added or
// removed in directories where given files are.
func Generate(target, filesGenerator string, files []string) string {
	return replacePlaceholders(depMkTemplate,
		"DEPS_GEN_FILES_GENERATOR", filesGenerator,
		"DEPS_GEN_ALL_FILES_STORED", strings.Join(files, " "),
		"DEPS_GEN_TARGET", target,
	)
}
