#!/bin/bash -e

if [ ! -e ./image/manifest ] ; then
	echo "Wrong directory"
	exit 1
fi

# Fail if "rootfs" already contains something. We delete it at the end.
[ -d image/rootfs ] && rmdir image/rootfs
mkdir image/rootfs

# Populate rootfs
(cd inspect && go build)
cp inspect/inspect image/rootfs/
mkdir image/rootfs/dir{1,2}
echo -n dir1 > image/rootfs/dir1/file
echo -n dir2 > image/rootfs/dir2/file

# Create base image
../bin/actool build --overwrite image rkt-inspect.aci

# Alternative images are created in tests themselves

# Cleanup
rm -rf image/rootfs
