#!/bin/bash -eu
#
# Builds an ACI containing a go implementation of an ACE validator
#

PREFIX="app-container/ace"

if ! [[ $0 =~ "${PREFIX}/build_aci" ]]; then 
	echo "invoke from repository root" 1>&2
	exit 255
fi

for typ in main sidekick; do 
	layoutdir="bin/ace_${typ}_layout"
	mkdir -p ${layoutdir}/rootfs
	cp bin/ace_validator ${layoutdir}/rootfs/
	cp ${PREFIX}/app_manifest_${typ}.json ${layoutdir}/app
	# now build the tarball, and sign it
	pushd ${layoutdir} >/dev/null
		# Set a consistent timestamp so we get a consistent hash
		# TODO(jonboulle): make this cleaner..
		for path in rootfs rootfs/ace_validator; do
			touch -a -m -d 1415660606 ${path}
		done
		../actool build --overwrite --app-manifest app rootfs/ ../ace_validator_${typ}.aci
		HASH=sha256-$(sha256sum ../ace_validator_${typ}.aci|awk '{print $1}')
		gzip -f ../ace_validator_${typ}.aci
		mv ../ace_validator_${typ}.aci.gz ../ace_validator_${typ}.aci
		gpg --cipher-algo AES256 --output ace_validator_${typ}.sig --detach-sig ../ace_validator_${typ}.aci
		mv ace_validator_${typ}.sig ../
	popd >/dev/null
	echo "Wrote ${typ} layout to      ${layoutdir}"
	echo "Wrote unsigned ${typ} ACI   bin/ace_validator_${typ}.aci"
	ln -s ${PWD}/bin/ace_validator_${typ}.aci bin/${HASH}
	echo "Wrote ${typ} layout hash    bin/${HASH}"
	echo "Wrote ${typ} ACI signature  bin/ace_validator_${typ}.sig"
done
