#!/bin/bash -eu
#
# Builds a TAF containing a go implementation of an ACE validator
#

PREFIX="app-container/ace"

if ! [[ $0 =~ "${PREFIX}/build_taf" ]]; then 
	echo "invoke from repository root" 1>&2
	exit 255
fi

for typ in main sidekick; do 
	rafdir="bin/ace_${typ}_raf"
	mkdir -p ${rafdir}/rootfs
	cp bin/ace_validator ${rafdir}/rootfs/
	cp ${PREFIX}/app_manifest_${typ}.json ${rafdir}/rootfs/app
	# now build the tarball, and sign it
	pushd ${rafdir} >/dev/null
		# Set a consistent timestamp so we get a consistent hash
		# TODO(jonboulle): make this cleaner..
		for path in app rootfs rootfs/ace_validator; do
			touch -a -m -d 1415660606 ${path}
		done
		../acfmt build --name coreos.com/ace-validator-${typ}-1.0.0 . ../ace_validator_${typ}.afs
		HASH=sha256-$(sha256sum ../ace_validator_${typ}.afs|awk '{print $1}')
		gzip -f ../ace_validator_${typ}.afs
		mv ../ace_validator_${typ}.afs.gz ../ace_validator_${typ}.afs
		gpg --cipher-algo AES256 --output ace_validator_${typ}.sig --detach-sig ../ace_validator_${typ}.afs
		mv ace_validator_${typ}.sig ../
	popd >/dev/null
	echo "Wrote ${typ} RAF to         ${rafdir}"
	echo "Wrote unsigned ${typ} TAF   bin/ace_validator_${typ}.afs"
	ln -s ${PWD}/bin/ace_validator_${typ}.afs bin/${HASH}
	echo "Wrote ${typ} RAF hash       bin/${HASH}"
	echo "Wrote ${typ} TAF signature  bin/ace_validator_${typ}.sig"
done
