S1_RF_COPY_SO_DEPS := $(STAGE1_COPY_SO_DEPS)
S1_RF_USR_STAMPS := $(STAGE1_USR_STAMPS)
S1_RF_SECONDARY_STAMPS := $(STAGE1_STAMPS)
S1_RF_ACIDIR := $(ACIDIR)
S1_RF_ACIROOTFSDIR := $(ACIROOTFSDIR)
S1_RF_INSTALL_FILES := $(STAGE1_INSTALL_FILES)
S1_RF_INSTALL_SYMLINKS := $(STAGE1_INSTALL_SYMLINKS)
S1_RF_INSTALL_DIRS := $(STAGE1_INSTALL_DIRS)
S1_RF_CREATE_DIRS := $(STAGE1_CREATE_DIRS)

_S1_RF_NAME_ := usr_from_$(S1_RF_FLAVOR)

INSTALL_DIRS += \
	$(S1_RF_ACIDIR):- \
	$(S1_RF_ACIROOTFSDIR):0750

$(call inc-one,$(_S1_RF_NAME_)/$(_S1_RF_NAME_).mk)

# Propagate the changes. Note that not all variables can be overridden
# - ACIDIR, ACIROOTFSDIR and so on are "read-only".
STAGE1_COPY_SO_DEPS += $(S1_RF_COPY_SO_DEPS)
STAGE1_USR_STAMPS += $(S1_RF_USR_STAMPS)
STAGE1_STAMPS += $(S1_RF_SECONDARY_STAMPS)
STAGE1_INSTALL_FILES += $(S1_RF_INSTALL_FILES)
STAGE1_INSTALL_SYMLINKS += $(S1_RF_INSTALL_SYMLINKS)
STAGE1_INSTALL_DIRS += $(S1_RF_INSTALL_DIRS)
STAGE1_CREATE_DIRS += $(S1_RF_CREATE_DIRS)

$(call undefine-namespaces,S1_RF _S1_RF)
