$(call setup-stamp-file,UFSB_STAMP)
UFSB_BASH_ON_ACI := $(ACIROOTFSDIR)/usr/bin/$(notdir $(BASH_SHELL))

STAGE1_STAMPS += $(UFSB_STAMP)
STAGE1_INSTALL_FILES += $(BASH_SHELL):$(UFSB_BASH_ON_ACI):-
STAGE1_INSTALL_DIRS += $(ACIROOTFSDIR)/usr/bin
STAGE1_INSTALL_SYMLINKS += usr/bin:$(ACIROOTFSDIR)/bin

$(UFSB_STAMP): $(UFSB_BASH_ON_ACI) | $(ACIROOTFSDIR)/bin
	touch "$@"

UFSB_STAMP :=
UFSB_BASH_ON_ACI :=
