LOCAL_NAME := reaper.sh
LOCAL_REAPER := $(MK_SRCDIR)/$(LOCAL_NAME)
LOCAL_ACI_REAPER := $(ACIROOTFSDIR)/$(LOCAL_NAME)

$(call setup-stamp-file,LOCAL_STAMP)

$(LOCAL_STAMP): $(LOCAL_ACI_REAPER)
	touch "$@"

STAGE1_INSTALL_FILES += $(LOCAL_REAPER):$(LOCAL_ACI_REAPER):0755
STAGE1_STAMPS += $(LOCAL_STAMP)

LOCAL_NAME :=
LOCAL_REAPER :=
LOCAL_ACI_REAPER :=
LOCAL_STAMP :=
